using Pkg

Pkg.activate(".")
Pkg.add("Agents")
Pkg.add("Graphs")
Pkg.add("GraphPlot")
Pkg.add("Compose")
Pkg.add("Cairo")
Pkg.add("Colors")
Pkg.add("Plots")
Pkg.add("DataFrames")
Pkg.add("Distributions")
Pkg.add("StatsPlots")
Pkg.add("BenchmarkTools")
Pkg.add("CSV")